# Apache HTTP Server Configuration File
# This is a basic configuration file for an Apache server with PHP support.
# It sets up the server to listen on port 80 and serve the LocalLoop website from /var/www/html/website.
# It also configures the server to recognize index.php as a default file.

# Server name
ServerName localhost

# Default files to serve
DirectoryIndex index.php index.html

# Document root directory
DocumentRoot /var/www/html/website

# Directory settings
# Enable directory listing and symbolic links
# Allow .htaccess overrides
# Allow access to all
<Directory /var/www/html/website>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

AddType font/woff2 .woff2
AddType font/woff .woff
AddType font/ttf .ttf
